export const QueryKeys = {
  CATEGORIES: "CATEGORIES",
  CUSTOMERS: "CUSTOMERS",
  ADMINS:"ADMINS",
  CITY:"CITY",
  PRODUCTS: "PRODUCTS",
  EMPLOYEE: "EMPLOYEE",
  STORELOCATION: "STORELOCATION",
  JOBPOSITION: "JOBPOSITION",
  OFFER: "OFFER",
  USER_BY_EMAIL: (email) => "USER_" + email,
};
